steps:
- name: 'golang'
  id: 'Test'
  args: ['ls'] 
- name: 'golang'
  id: 'Test'
  args: ['go', 'test', '-v', '"./..."'] 
- name: 'gcr.io/cloud-builders/docker'
  id: 'Docker build'
  args: ['build', '-t', 'eu.gcr.io/$PROJECT_ID/gogs:$BUILD_ID', '-t', 'eu.gcr.io/$PROJECT_ID/gogs:latest', '.']
- name: 'gcr.io/cloud-builders/docker'
  id: 'Push buildID'
  args: ['push', 'eu.gcr.io/gogs-project/gogs:$BUILD_ID']

- name: 'gcr.io/cloud-builders/docker'
  id: 'Push latest'
  args: ['push', 'eu.gcr.io/gogs-project/gogs:latest']
  
- name: 'gcr.io/cloud-builders/gke-deploy'
  id: 'Apply deploy'
  args:
  - 'apply'
  - '--filename=./k8s-deploy/deployment.yaml'
  - '--namespace=default'
  - '--cluster=gogs-gke'
  - '--location=europe-west3'
