steps:
- name: 'golang'
  id: 'Test'
  args: ['bash', 'test.sh'] 
- name: 'gcr.io/cloud-builders/docker'
  id: 'Docker build'
  args: ['build', '-t', 'eu.gcr.io/$PROJECT_ID/gogs:$BUILD_ID', '-t', 'eu.gcr.io/$PROJECT_ID/gogs:latest', '.']
- name: 'gcr.io/cloud-builders/docker'
  id: 'Push buildID'
  args: ['push', 'eu.gcr.io/gogs-project/gogs:$BUILD_ID']

- name: 'gcr.io/cloud-builders/docker'
  id: 'Push latest'
  args: ['push', 'eu.gcr.io/gogs-project/gogs:latest']
  
- name: 'gcr.io/cloud-builders/gke-deploy'
  id: 'Deploy resources'
  args:
  - 'apply'
  - '--filename=./k8s-deploy/deployment.yaml'
  - '--namespace=default'
  - '--cluster=gogs-gke'
  - '--location=europe-west3'
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  env:
  - CLOUDSDK_COMPUTE_REGION=europe-west3
  - CLOUDSDK_CONTAINER_CLUSTER=gogs-gke
  id: 'Update image'
  entrypoint: 'kubectl'
  args: ['set', 'image', 'deployment/gogs-deployment', 'gogs=eu.gcr.io/gogs-project/gogs:$BUILD_ID']
timeout: 900s
